#!/usr/bin/env python3
"""Dump a human-readable reference of item ids from items_game.txt.

Produces docs/item_ids.txt listing, by category, the definition index + def name
for cases, keys, agents, operation items (coins/passes/stars), plus every
item-set / collection (Riptide, Dust, etc.). Use these def names in the Operation
Shop schema (operation_util.js m_rewardSchema) and with `admin.py grant-item`.

Usage:
  python3 build_item_ids.py [--items-game ../items_game.txt] [--out ../docs/item_ids.txt]
"""

from __future__ import annotations

import argparse
import os

import kvparser

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(HERE)


def resolve(prefab_map, item, field, _seen=None):
    """Resolve a field through the prefab chain (space-separated prefab list)."""
    if field in item:
        return item[field]
    _seen = _seen or set()
    prefabs = str(item.get("prefab", "")).split()
    for p in prefabs:
        if p in _seen:
            continue
        _seen.add(p)
        parent = prefab_map.get(p)
        if isinstance(parent, dict):
            val = resolve(prefab_map, parent, field, _seen)
            if val is not None:
                return val
    return None


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--items-game", default=os.path.join(REPO, "items_game.txt"))
    ap.add_argument("--out", default=os.path.join(REPO, "docs", "item_ids.txt"))
    args = ap.parse_args()

    root = kvparser.parse_file(args.items_game)
    ig = root.get("items_game", root)
    items = ig.get("items", {}) or {}
    prefab_map = ig.get("prefabs", {}) or {}
    item_sets = ig.get("item_sets", {}) or {}

    cases, keys, agents, operation, misc_collectibles = [], [], [], [], []

    for defidx, it in items.items():
        if not isinstance(it, dict) or not defidx.isdigit():
            continue
        name = it.get("name", "")
        prefab = str(it.get("prefab", ""))
        item_class = resolve(prefab_map, it, "item_class") or ""
        has_series = "set supply crate series" in (it.get("attributes", {}) or {})
        low = (name + " " + prefab).lower()

        row = (int(defidx), name)
        if has_series or ("weapon_case" in prefab and "key" not in prefab):
            cases.append(row)
        elif "key" in low and ("case_key" in prefab or "key" in name.lower()):
            keys.append(row)
        elif item_class == "customplayer" or "customplayer" in prefab:
            agents.append(row)
        elif any(k in low for k in ("coin", "operation", "season", "pass", "_stars", "medal")):
            operation.append(row)

    def dump(f, title, rows):
        f.write(f"\n{'='*70}\n{title} ({len(rows)})\n{'='*70}\n")
        for defidx, name in sorted(rows):
            f.write(f"  {defidx:>7}  {name}\n")

    os.makedirs(os.path.dirname(args.out), exist_ok=True)
    with open(args.out, "w", encoding="utf-8") as f:
        f.write("CS:GO Revival - item id reference (generated by build_item_ids.py)\n")
        f.write("Columns: <def_index>  <definition name>\n")
        f.write("Use the definition name in operation_util.js m_rewardSchema; use the\n")
        f.write("def_index with `admin.py grant-item --def-index <n>`.\n")
        dump(f, "OPERATION (coins / passes / stars / medals)", operation)
        dump(f, "CASES", cases)
        dump(f, "KEYS", keys)
        dump(f, "AGENTS (playable characters)", agents)

        # collections / item sets (Riptide, Dust, etc.)
        f.write(f"\n{'='*70}\nCOLLECTIONS / ITEM SETS ({len(item_sets)})\n{'='*70}\n")
        f.write("  set key                              display-name token\n")
        for setkey, sdata in sorted(item_sets.items()):
            disp = ""
            if isinstance(sdata, dict):
                disp = sdata.get("name", "") or sdata.get("set_text", "")
            f.write(f"  {setkey:36} {disp}\n")

    print(f"[item_ids] cases={len(cases)} keys={len(keys)} agents={len(agents)} "
          f"operation={len(operation)} collections={len(item_sets)}")
    print(f"[item_ids] wrote {args.out}")


if __name__ == "__main__":
    main()
