param(
    [string]$CsgoDir = "C:\Program Files (x86)\Steam\steamapps\common\csgo legacy"
)

$ErrorActionPreference = "Stop"

# Normalize the caller-provided Windows path before using it for Test-Path/Join-Path.
$CsgoDir = [IO.Path]::GetFullPath($CsgoDir)

if (-not (Test-Path (Join-Path $CsgoDir "csgo"))) {
    throw "CS:GO Legacy folder not found: $CsgoDir"
}

$adminConfig = Join-Path $PSScriptRoot "server_agent.json"
if (-not (Test-Path $adminConfig)) {
    throw "server_agent.json not found next to this installer."
}
$cfg = Get-Content $adminConfig -Raw | ConvertFrom-Json
$admins = @($cfg.admin_steamids | ForEach-Object { [string]$_ } | Where-Object { $_ -match '^[0-9]{17}$' })
if ($admins.Count -lt 1) {
    throw "No admin_steamids configured. Run SET_ADMIN.ps1 <SteamID64> first."
}

$work = Join-Path $env:TEMP ("revival-admin-" + [guid]::NewGuid().ToString("N"))
New-Item $work -ItemType Directory -Force | Out-Null
try {
    $mmZip = Join-Path $work "metamod.zip"
    $smZip = Join-Path $work "sourcemod.zip"

    Write-Host "[1/5] Downloading MetaMod:Source 1.12..." -ForegroundColor Yellow
    Invoke-WebRequest "https://mms.alliedmods.net/mmsdrop/1.12/mmsource-1.12.0-git1227-windows.zip" -OutFile $mmZip -UseBasicParsing
    Write-Host "[2/5] Downloading SourceMod 1.12..." -ForegroundColor Yellow
    Invoke-WebRequest "https://sm.alliedmods.net/smdrop/1.12/sourcemod-1.12.0-git7253-windows.zip" -OutFile $smZip -UseBasicParsing

    $mmDir = Join-Path $work "mm"
    $smDir = Join-Path $work "sm"
    Expand-Archive $mmZip -DestinationPath $mmDir -Force
    Expand-Archive $smZip -DestinationPath $smDir -Force

    Write-Host "[3/5] Installing server extensions..." -ForegroundColor Yellow
    Copy-Item (Join-Path $mmDir "*") $CsgoDir -Recurse -Force
    Copy-Item (Join-Path $smDir "*") $CsgoDir -Recurse -Force

    # MetaMod's Windows package normally supplies addons\\metamod.vdf.
    # If a security product or an incomplete extraction removed only the VDF,
    # restore the standard loader file as long as the actual MetaMod DLL exists.
    $metaVdf = Join-Path $CsgoDir "addons\metamod.vdf"
    $metaDll = Join-Path $CsgoDir "addons\metamod\bin\server.dll"
    if (-not (Test-Path $metaVdf)) {
        if (-not (Test-Path $metaDll)) {
            throw "MetaMod installation is incomplete: neither addons\\metamod.vdf nor addons\\metamod\\bin\\server.dll exists."
        }
        $metaAddons = Split-Path $metaVdf -Parent
        New-Item $metaAddons -ItemType Directory -Force | Out-Null
        @'
"Plugin"
{
	"file"	"addons/metamod/bin/server"
}
'@ | Set-Content $metaVdf -Encoding ASCII -NoNewline
        Write-Host "    Restored missing MetaMod loader: $metaVdf" -ForegroundColor Green
    }

    $sm = Join-Path $CsgoDir "addons\sourcemod"
    $adminFile = Join-Path $sm "configs\admins_simple.ini"
    New-Item (Split-Path $adminFile -Parent) -ItemType Directory -Force | Out-Null

    $lines = @("// CS:GO Revival owner/admins - generated by SET_ADMIN.ps1")
    foreach ($id in $admins) {
        $lines += '"' + $id + '" "99:z"'
    }
    Set-Content $adminFile $lines -Encoding UTF8

    Write-Host "[4/5] Installing Revival admin plugin..." -ForegroundColor Yellow
    $source = Join-Path $PSScriptRoot "revival_admin.sp"
    if (-not (Test-Path $source)) {
        throw "revival_admin.sp not found next to installer."
    }
    $sourceDest = Join-Path $sm "scripting\revival_admin.sp"
    $pluginDest = Join-Path $sm "plugins\revival_admin.smx"
    New-Item (Split-Path $sourceDest -Parent) -ItemType Directory -Force | Out-Null
    New-Item (Split-Path $pluginDest -Parent) -ItemType Directory -Force | Out-Null
    Copy-Item $source $sourceDest -Force

    $spcomp = Join-Path $sm "scripting\spcomp.exe"
    if (-not (Test-Path $spcomp)) {
        throw "SourceMod compiler missing: $spcomp"
    }
    & $spcomp $sourceDest -o $pluginDest
    if ($LASTEXITCODE -ne 0 -or -not (Test-Path $pluginDest)) {
        throw "revival_admin.sp failed to compile."
    }

    Write-Host "[5/5] Verifying..." -ForegroundColor Yellow
    foreach ($p in @(
        (Join-Path $CsgoDir "addons\metamod.vdf"),
        (Join-Path $sm "sourcemod_mm.dll"),
        (Join-Path $sm "configs\admins_simple.ini"),
        $pluginDest
    )) {
        if (-not (Test-Path $p)) {
            throw "Admin runtime file missing: $p"
        }
    }

    Write-Host "REVIVAL_ADMIN_MODERATION_V1 installed." -ForegroundColor Green
    Write-Host "Admin commands: sm_rcon / !rcon, sm_bangun / !bangun, sm_bangoff, sm_revival_unban."
    Write-Host "Restart srcds after installation."
}
finally {
    Remove-Item $work -Recurse -Force -ErrorAction SilentlyContinue
}
