param(
    [Parameter(Mandatory=$true)]
    [string]$SteamId64
)
$ErrorActionPreference = "Stop"
if ($SteamId64 -notmatch '^[0-9]{17}$') {
    throw "SteamID64 must be 17 digits."
}
$path = Join-Path $PSScriptRoot "server_agent.json"
if (-not (Test-Path $path)) {
    throw "server_agent.json not found. Copy server_agent.example.json first."
}
$data = Get-Content $path -Raw | ConvertFrom-Json
$data.admin_steamids = @($SteamId64)
$data | ConvertTo-Json -Depth 8 | Set-Content $path -Encoding UTF8

# Keep SourceMod's native admin database in sync too. The installer can also
# regenerate this file, but writing it here makes SET_ADMIN immediately
# authoritative on an already-installed admin runtime.
$csgoDir = $data.csgo_dir
if ([string]::IsNullOrWhiteSpace($csgoDir)) {
    $csgoDir = "C:\Program Files (x86)\Steam\steamapps\common\csgo legacy"
}
$adminsSimple = Join-Path $csgoDir "addons\sourcemod\configs\admins_simple.ini"
New-Item (Split-Path $adminsSimple -Parent) -ItemType Directory -Force | Out-Null
Set-Content $adminsSimple @(
    "// CS:GO Revival owner/admin - generated by SET_ADMIN.ps1",
    '"' + $SteamId64 + '" "99:z"'
) -Encoding UTF8

Write-Host "Server admin configured: $SteamId64"
Write-Host "SourceMod admin database updated: $adminsSimple"
Write-Host "Restart srcds/start-agent.bat after this change."
